SalesManagementSystem/SalesManagementSystem/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;


namespace SalesManagementSystem.Models
{
    public class Product
    {
        [Display(Name = "Product Id")]

        public int id { get; set; }
        [Display(Name = "Product Name")]

        public string pname { get; set; }
        [Display(Name = "Product Company")]

        public string pcompany { get; set; }
        [Display(Name = "Product Type")]

        public string ptype { get; set; }
        [Display(Name = "Product Ptice")]

        public int price { get; set; }
        [Display(Name = "Product Stock")]

        public int stock { get; set; }

        DBAccess obj = new DBAccess();

        public List<Product> productlist()
        {
            List<Product> clist = new List<Product>();
            obj.OpenCon();
            string q = "Select * from product";
            obj.cmd = new SqlCommand(q, obj.con);
            SqlDataReader sdr = obj.cmd.ExecuteReader();
            while (sdr.Read())
            {
                Product s = new Product();
                s.id = int.Parse(sdr[0].ToString());
                s.pname = sdr[1].ToString();
                s.pcompany = sdr[2].ToString();
                s.ptype = sdr[3].ToString();
                s.price = int.Parse(sdr[4].ToString());
                s.stock = int.Parse(sdr[5].ToString());
                clist.Add(s);
            }
            sdr.Close();
            obj.CloseCon();
            return clist;
        }
    }
}

SalesManagementSystem/SalesManagementSystem/Models/ProductType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Data.SqlClient;


namespace SalesManagementSystem.Models
{
    public class ProductType
    {
        public int id { get; set; }

        [Display(Name = "Enter Product Title")]
        public string title { get; set; }
        [Display(Name = "Decription")]
        public string decscription { get; set; }

        DBAccess obj = new DBAccess();

        public List<ProductType> GetType()
        {
            List<ProductType> ulist = new List<ProductType>();
            obj.OpenCon();
            string q = "Select * from ProductType";
            obj.cmd = new SqlCommand(q, obj.con);
            SqlDataReader sdr = obj.cmd.ExecuteReader();
            while (sdr.Read())
            {
                ProductType u = new ProductType();
                u.id = int.Parse(sdr[0].ToString());
                u.title = sdr[1].ToString();
                u.decscription = sdr[2].ToString();

                ulist.Add(u);
            }
            sdr.Close();
            obj.CloseCon();
            return ulist;
        }
    }
}

SalesManagementSystem/SalesManagementSystem/Models/Sales.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.SqlClient;

namespace SalesManagementSystem.Models
{
    public class Sales
    {
        public string OrderId { get; set; }
        public string OrderDate { get; set; }
        public string CustomerName { get; set; }
        public string CustomerNumber { get; set; }
        public string SelectProduct { get; set; }
        public int Cost { get; set; }
        public int Quantity { get; set; }
        public int Total { get; set; }

        DBAccess obj = new DBAccess();

        public List<Sales> Saleslist()
        {
            List<Sales> clist = new List<Sales>();
            obj.OpenCon();
            string q = "Select * from sales";
            obj.cmd = new SqlCommand(q, obj.con);
            SqlDataReader sdr = obj.cmd.ExecuteReader();
            while (sdr.Read())
            {
                Sales s = new Sales();
                s.OrderId = sdr[0].ToString();
                s.OrderDate = sdr[1].ToString();
                s.CustomerName = sdr[2].ToString();
                s.CustomerNumber = sdr[3].ToString();
                s.SelectProduct = sdr[4].ToString();
                s.Cost = int.Parse(sdr[5].ToString());
                s.Quantity = int.Parse(sdr[7].ToString());
                s.Total= int.Parse(sdr[6].ToString());
                clist.Add(s);
            }
            sdr.Close();
            obj.CloseCon();
            return clist;
        }

        public Sales SalesDetail(int id)
        {
            Sales s = new Sales();
            obj.OpenCon();
            string q = "Select * from sales where OrderId='"+id+"'";
            obj.cmd = new SqlCommand(q, obj.con);
            SqlDataReader sdr = obj.cmd.ExecuteReader();
            sdr.Read();

            s.OrderId = sdr[0].ToString();
            s.OrderDate = sdr[1].ToString();
            s.CustomerName = sdr[2].ToString();
            s.CustomerNumber = sdr[3].ToString();
            s.SelectProduct = sdr[4].ToString();
            s.Cost = int.Parse(sdr[5].ToString());
            s.Quantity = int.Parse(sdr[6].ToString());

            sdr.Close();
            obj.CloseCon();

            return s;
        }
    }
}

SalesManagementSystem/SalesManagementSystem/Controllers/SalesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SalesManagementSystem.Models;
using System.Data.SqlClient;
using System.Data;
using System.IO;

namespace SalesManagementSystem.Controllers
{
    public class SalesController : Controller
    {
        DBAccess dbaobj = new DBAccess();
        // GET: Sales
        //AddCompany
        public ActionResult AddCompany()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddCompany(Company c)
        {

            if (ModelState.IsValid)
            {
                string filename = c.logo.FileName;
                string ext = Path.GetExtension(filename);
                string[] extarr = { ".png", ".PNG", ".jpg", ".bmp", ".JPG" };
                if (extarr.Contains(ext))
                {
                    string ufilename = c.cname.Trim() + ext;
                    string path = Path.Combine(Server.MapPath("/images"), ufilename);
                    c.logo.SaveAs(path);
                    c.filepath = "/images/" + ufilename;
                    string q = "insert into company values('" + c.cname + "','" + c.filepath + "','" + c.mobile + "','" + c.email + "','" + c.websiteurl + "','" + c.country+ "') ";
                    dbaobj.InsertUpdateDelete(q);
                    Response.Write("<script>alert('" + c.cname + " Company Registered!');</script>");
                }
            }
            return View(c);
        }
        //Product Type
        public ActionResult ProductType()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ProductType(ProductType pt)
        {
            string q = "insert into producttype values('"+pt.title+"','"+pt.decscription+"')";
            dbaobj.InsertUpdateDelete(q);
            return View();
        }
        //Add Product

        public ActionResult AddProduct()
        {
            //ProductType
            List<SelectListItem> plist = new List<SelectListItem>();
            string pr = "select title from producttype";
            dbaobj.OpenCon();
            dbaobj.cmd = new SqlCommand(pr, dbaobj.con);
            SqlDataReader sdr1 = dbaobj.cmd.ExecuteReader();
            while (sdr1.Read())
            {
                plist.Add(new SelectListItem { Text = "" + sdr1["title"].ToString() + "", Value = "" + sdr1["title"].ToString() + "" });
            }
            sdr1.Close();
            dbaobj.CloseCon();

            //Company
            List<SelectListItem> clist = new List<SelectListItem>();
            string com = "select cname from Company";
            dbaobj.OpenCon();
            dbaobj.cmd = new SqlCommand(com, dbaobj.con);
            SqlDataReader sdr = dbaobj.cmd.ExecuteReader();
            while (sdr.Read())
            {
                clist.Add(new SelectListItem { Text = "" + sdr["cname"].ToString() + "", Value = "" + sdr["cname"].ToString() + "" });
            }
            sdr.Close();
            dbaobj.CloseCon();



            TempData["plist"] = plist.ToList();
            TempData["clist"] = clist.ToList();

            return View();
        }
        [HttpPost]
        public ActionResult AddProduct(Product p)
        {         
            string q = "insert into product values('" + p.pname + "','" + p.pcompany + "','" + p.ptype + "','" + p.price + "','" + p.stock + "')";
            dbaobj.InsertUpdateDelete(q);
            return View();
        }
        //Sales
        public ActionResult AddSales()
        {
            List<SelectListItem> slist = new List<SelectListItem>();
            string s = "select pname,price from product";
            dbaobj.OpenCon();
            dbaobj.cmd = new SqlCommand(s, dbaobj.con);
            SqlDataReader sdr = dbaobj.cmd.ExecuteReader();
            while (sdr.Read())
            {
                slist.Add(new SelectListItem { Text = "" + sdr["pname"].ToString() + "", Value = "" + sdr["pname"].ToString() + "" });
            }
            sdr.Close();
            dbaobj.CloseCon();
            TempData["slist"] = slist;
            return View();
        }
        [HttpPost]
        public ActionResult AddSales(Sales s)
        {
            int total = s.Cost * s.Quantity;
            int qun = s.Quantity;
            string dt = DateTime.Now.ToShortDateString();
          //  string q = "update product set stock='"++"' where OrderId='" + s.OrderId + "'";

            string q = "insert into sales values('SM00" + s.CustomerNumber + "','" + dt + "','" + s.CustomerName + "','" + s.CustomerNumber + "','" + s.SelectProduct + "','" + s.Cost + "', '"+total+"' ,'" + s.Quantity + "')";
            dbaobj.InsertUpdateDelete(q);
            return View();
        }

        public ActionResult ProductTypeReport()
        {
            ProductType PT = new ProductType();
            return View(PT.GetType());
        }
        public ActionResult CompanyReport()
        {
            Company s = new Company();
            return View(s.Companylist());
        }
        public ActionResult ProductReport()
        {
            Product s = new Product();
            return View(s.productlist());
        }
        public ActionResult SalesReport()
        {
            Sales s = new Sales();
            return View(s.Saleslist());
        }



        public ActionResult DeleteSale(int id)
        {
            string q = "Delete from sales where OrderId='" + id + "'";
            dbaobj.InsertUpdateDelete(q);
            return RedirectToAction("DetailSale");
        }
        public ActionResult DetailSale(int id)
        {
            Sales s = new Sales();
            return View(s.SalesDetail(id));
        }
        public ActionResult EditSale(int id)
        {
            Sales s = new Sales();
            return View(s.SalesDetail(id));
        }
        [HttpPost]
        public ActionResult EditSale(Sales s)
        {
            string q = "update sales set CustomerName='" + s.CustomerName + "',CustomerNumber='" + s.CustomerNumber + "',SelectProduct='" + s.SelectProduct + "',Cost='" + s.Cost + "',Quantity='" + s.Quantity + "' where OrderId='" + s.OrderId+ "'";
            dbaobj.InsertUpdateDelete(q);
            return RedirectToAction("DetailSale");
        }
    }
}

SalesManagementSystem/SalesManagementSystem/Views/Sales/AddCompany.cshtml
@model SalesManagementSystem.Models.Company

@{
    ViewBag.Title = "AddCompany";
    Layout = "~/Views/Shared/_dashboard.cshtml";

    List<SelectListItem> countrys = new List<SelectListItem>()
{
        new SelectListItem {Text="Pakistan",Value="Pakistan" },
        new SelectListItem {Text="USA",Value="USA" },
        new SelectListItem {Text="India",Value="India" },
        new SelectListItem {Text="Canada",Value="Canada" },
        new SelectListItem {Text="Turkey",Value="Turkey" },
    };
}
<hr />
<hr />
<hr />
<hr />
<hr />
<div class="container">
    <div class="row">
        <div class="col-lg-12">

            @using (Html.BeginForm("AddCompany", "Sales", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {


                <div class="form-horizontal">
                    <h4 class="text-center text-primary">Add Company</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.cname, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.cname, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.cname, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-10">
                            @Html.LabelFor(model => model.logo, htmlAttributes: new { @class = "control-label col-md-2" })

                            @Html.TextBoxFor(model => model.logo, new { type = "file", htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.logo, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.mobile, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.mobile, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.mobile, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.websiteurl, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.websiteurl, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.websiteurl, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.country, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.country, countrys, "Select")
                            @Html.ValidationMessageFor(model => model.country, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Add" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            }
            @if (IsPost)
            {
                <h2>Your Logo</h2>


                <img src="@Model.filepath" height="200" width="200" />
            }

        </div>
    </div>
</div>

SalesManagementSystem/SalesManagementSystem/Views/Sales/AddProduct.cshtml
@model SalesManagementSystem.Models.Product

@{
    ViewBag.Title = "AddProduct";
    Layout = "~/Views/Shared/_dashboard.cshtml";

    var clist = TempData["clist"] as List<SelectListItem> ?? new List<SelectListItem>();
    

    var plist = TempData["plist"] as List<SelectListItem> ?? new List<SelectListItem>();
  
}
<hr />
<hr />
<hr />
<hr />
<hr />
<h2 class="text-center text-primary">Add Product</h2>
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.pname, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.pname, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.pname, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-10">
                            @Html.LabelFor(model => model.pcompany, htmlAttributes: new { @class = "control-label col-md-2" })

                            @Html.DropDownListFor(model => model.pcompany, (List<SelectListItem>)clist, "-------")
                            @Html.ValidationMessageFor(model => model.pcompany, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-10">
                            @Html.LabelFor(model => model.ptype, htmlAttributes: new { @class = "control-label col-md-2" })

                            @Html.DropDownListFor(model => model.ptype, (List<SelectListItem>)plist, "-------")
                            @Html.ValidationMessageFor(model => model.ptype, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.stock, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.stock, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.stock, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Add" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            }

            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div>
    </div>
</div>

SalesManagementSystem/SalesManagementSystem/Views/Sales/AddSales.cshtml
@model SalesManagementSystem.Models.Sales

@{
    ViewBag.Title = "AddSales";
    Layout = "~/Views/Shared/_dashboard.cshtml";


    var slist = TempData["slist"] as List<SelectListItem> ?? new List<SelectListItem>();
}
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
</head>
<body>

    <hr />
    <hr />
    <hr />
    <hr />
    <hr />
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h2 class="text-center text-primary">Add Sales</h2>

                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                        <div class="form-group">

                            <div class="col-md-10">
                                Customer Name
                                @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">

                            <div class="col-md-10">
                                Customer Number
                                @Html.EditorFor(model => model.CustomerNumber, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.CustomerNumber, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">

                            <div class="col-md-10">
                                Select Product
                                @*   @Html.DropDownList("Add",null,new { onchange="document.location.href='/Default/Index?value='+this.value;"})*@
                                @Html.DropDownListFor(model => model.SelectProduct, (List<SelectListItem>)slist, "-------")                                @Html.ValidationMessageFor(model => model.SelectProduct, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        @*    <div class="form-group">
                                  Cost
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="text" id="val" readonly="readonly" />
                                </div>
                            </div>*@
                        <div class="form-group">

                            <div class="col-md-10">
                                Product Cost
                                @Html.EditorFor(model => model.Cost, new {htmlAttributes = new {@id="val", @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">

                            <div class="col-md-10">
                                Product Quantity
                                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Add" class="btn btn-primary" />
                            </div>
                        </div>
                    </div>
                }
                <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
            @*    <script>
                    function seletedtext(ddlitem) {
                        var selvalue = ddlitem.value;
                        var seltext = ddlitem.options[ddlitem.seletedIndex].innerHTML;
                        $('#val').val(seltext);
                    }
                </script>*@
            </div>
        </div>
    </div>
</body>
</html>

SalesManagementSystem/SalesManagementSystem/Views/Sales/CompanyReport.cshtml
@model IEnumerable<SalesManagementSystem.Models.Company>

@{
    ViewBag.Title = "CompanyReport";
    Layout = "~/Views/Shared/_dashboard.cshtml";
}
<hr />
<hr />
<hr />
<hr />
<hr />
<h2 class="text-center text-primary">Company Report</h2>

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <table class="table table-striped table-hover table-bordered">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.cname)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.logo)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.mobile)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.email)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.websiteurl)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.country)
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.cname)
                        </td>
                        <td>
                            <img src="@item.filepath" height="100" width="100" />

                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.mobile)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.email)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.websiteurl)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.country)
                        </td>
@*                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                            @Html.ActionLink("Details", "Details", new { id = item.id }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.id })
                        </td>*@
                    </tr>
                }

            </table>
</div>
</div></div>

SalesManagementSystem/SalesManagementSystem/Views/Sales/DeleteSale.cshtml
@model SalesManagementSystem.Models.Sales

@{
    ViewBag.Title = "DeleteSale";
    Layout = "~/Views/Shared/_dashboard.cshtml";
}

<h2>DeleteSale</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Sales</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OrderId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SelectProduct)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SelectProduct)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SalesManagementSystem/SalesManagementSystem/Views/Sales/DetailSale.cshtml
@model SalesManagementSystem.Models.Sales

@{
    ViewBag.Title = "DetailSale";
    Layout = "~/Views/Shared/_dashboard.cshtml";
}

<h2>DetailSale</h2>

<div>
    <h4>Sales</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OrderId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SelectProduct)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SelectProduct)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>